scss_files: 'src/sass/**/*.css.scss'

exclude:
  - 'src/sass/_normalize.scss'

linters:
  Comment:
    exclude:
      - 'src/sass/_functions.scss'
      - 'src/sass/_meta.scss'
  NameFormat:
    exclude:
      - 'src/sass/_widgets.scss'
